networks:
  mynetwork:
    driver: bridge

services:
  rustapp:
    container_name: rustapp
    env_file: "./.env"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    ports:
      - 127.0.0.1:8080:3000
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    container_name: pg-db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  pgdata: {}
