-- create role table
CREATE TABLE IF NOT EXISTS USERS (
    id UUID PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    wins int DEFAULT 0
);
